# Generated by Django 5.1.3 on 2024-11-12 07:24

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('plan_name', models.CharField(help_text='Plan Name is Mendatory*', max_length=80, verbose_name='Plan Name')),
                ('plan_price', models.CharField(help_text='Plan Price is Mendatory*', max_length=20, verbose_name='Plan Price')),
                ('price_basis', models.CharField(choices=[('YEAR', 'year'), ('MONTH', 'month'), ('WEEK', 'week'), ('DAY', 'day')], default='MONTH', max_length=100, verbose_name='')),
                ('plan_subdesc', models.CharField(blank=True, help_text='This field is optional', max_length=200, null=True, verbose_name='Plan Subdescription')),
                ('plan_service_desc', wagtail.fields.RichTextField(blank=True)),
                ('plan_cta', models.CharField(help_text='Text to display on Call to Action', max_length=50, verbose_name='')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricingPagePlan', to='pricing.pricingpage')),
                ('plan_cta_link', models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planCtaLink', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
