# Generated by Django 5.1.3 on 2024-11-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(help_text='Banner Title *', max_length=100, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, help_text='Banner Subtitle ', max_length=300, null=True, verbose_name='Banner Sub Title')),
                ('banner_cta', models.CharField(help_text='Text to display on Call to Action', max_length=50, verbose_name='')),
                ('banner_cta_url', models.URLField(blank=True, help_text='if banner_cta_link not found. Then this url will work', max_length=250, null=True, verbose_name='')),
                ('banner_cta_link', models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homePageBannerLink', to='wagtailcore.page')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
